name: media

services:
  komga:
    image: gotson/komga
    container_name: komga
    user: '${PUID}:${PGID}'
    environment:
      - TZ=${TZ}
    ports:
      - 25600:25600
    restart: always
    volumes:
      - ${DOCKER_DATA}/komga/config:/config
      - ${DOCKER_DATA}/komga/data:/data
      - ${DOCKER_DATA}/komga/tmp:/tmp
      - ${RESOURCE_DATA}:/resource
      - ${QBITTORRENT_DATA}:/qbit

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: '${PUID}:${PGID}'
    environment:
      - TZ=${TZ}
      - HTTP_PROXY=http://mihomo:7890
      - HTTPS_PROXY=http://mihomo:7890
    volumes:
      - ${DOCKER_DATA}/jellyfin/config:/config
      - ${DOCKER_DATA}/jellyfin/cache:/cache
      - ${DOCKER_DATA}/jellyfin/media:/media
      - ${RESOURCE_DATA}:/resource
      - ${QBITTORRENT_DATA}:/qbit
    ports:
      - 8096:8096
      - 7359:7359/udp
    restart: always
