name: tool

services:
  openlist:
    image: 'openlistteam/openlist:latest'
    container_name: openlist
    environment:
      - TZ=${TZ}
      - UMASK=022
    user: '${PUID}:${PGID}'
    volumes:
      - ${DOCKER_DATA}/openlist:/opt/openlist/data
      - ${RESOURCE_DATA}:/resource
      - ${QBITTORRENT_DATA}:/qbit
    restart: always
    ports:
      - 5244:5244

  volix:
    image: djwl/volix:latest
    container_name: volix
    restart: always
    environment:
      - TZ=${TZ}
    ports:
      - '3000:3000'
    volumes:
      - ${DOCKER_DATA}/volix:/app/data

  metatube:
    image: ghcr.io/metatube-community/metatube-server:latest
    container_name: metatube
    restart: always
    depends_on:
      - mihomo
    ports:
      - 8077:8080
    environment:
      - TZ=${TZ}
      - HTTP_PROXY=http://mihomo:7890
      - HTTPS_PROXY=http://mihomo:7890
    volumes:
      - ${DOCKER_DATA}/metatube:/config
    command: -dsn /config/metatube.db

  shipyard:
    image: soulter/shipyard-bay:latest
    ports:
      - '8156:8156'
      - '8157:8157'
    environment:
      - PORT=8156
      - DATABASE_URL=sqlite+aiosqlite:///./data/bay.db
      - ACCESS_TOKEN=secret-token
      - MAX_SHIP_NUM=10
      - BEHAVIOR_AFTER_MAX_SHIP=reject
      - CONTAINER_DRIVER=docker
      - DOCKER_NETWORK=nas_default
      - DOCKER_IMAGE=soulter/shipyard-ship:latest
      - SHIP_DATA_DIR=${DOCKER_DATA}/shipyard/ship_mnt_data
      - DEFAULT_SHIP_CPUS=1.0
      - DEFAULT_SHIP_MEMORY=512m
    volumes:
      - ${DOCKER_DATA}/shipyard/bay_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
