# 利用GitHub Action自动构建多框架的docker镜像
name: Build Docker Image

on:
  push:
    tags:
      - 'v*'

  pull_request:
    tags:
      - 'v*'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Build Frontend
        run: |
          npm install -g pnpm@8.15.9
          cd frontend
          pnpm install
          pnpm run build
          cd ..
          rm -rf public
          mv -f frontend/dist public

      - name: Commit Public
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "feat: update assets"
          git push

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/volix:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/volix:${{ github.ref_name }}
